### ISSUE TITLE
On the Data Upload tutorial page: URL for Internet Archive help is 404ing

### ISSUE THREAD

**Issue by dlstrong** [sucho-archiving/sucho-archiving.github.io#19]
**Describe the bug**
On https://www.sucho.org/data-upload and in the metadata Google doc, the Internet Archive help page (https://help.archive.org/category/archive-org/uploading/) is returning 404 on 3/10

**To Reproduce**
1. Go to https://help.archive.org/category/archive-org/uploading/
2. There's a 404

**Expected behavior**
I thought there would be a page there

**Screenshots**
Sorry, no screen shots

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser [e.g. chrome, safari]: Chrome
 - Version [e.g. 22]: honestly I don't think my browser version matters here

**Additional context**
I think that should cover it? I don't know what the intended IA help file contains or where it actually lives or I would have made a pull request to fix it, but in the absence of knowing how to fix the broken link, this is what I've got

**Comment by storytracer** [comment]
Fixed
